//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Classified.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAC_TicketVerification
    {
        public System.Guid TicketId { get; set; }
        public Guid UserId { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public DateTime CreatedDate { get; set; }
    
        public virtual TAC_User TAC_User { get; set; }
    }
}
